name: Deploy Fastify

on:
  push:
    branches:
      - dev

jobs:
  deploy:
  runs-on: [self-hosted, linux ]

    steps:
      - uses: actions/checkout@v4

      - name: Build & Run
        run: |
          cd backend-fastify-setting || true
          corepack enable
          yarn install
          yarn build
          pkill node || true
          nohup yarn start > app.log 2>&1 &
